### ISSUE TITLE
The annoying old compiler

### ISSUE THREAD

**Issue by AlessandroSangiuliano** [neozeed/xMach#3]
Hello, can I ask you, when you have a bit of time, to provide the old gcc compiler and binutils? 

oskit archives seems unreacheable right now.

Thank you

**Comment by neozeed** [comment]
Sure let me dig it up, I’d documented it on my blog virtuallyfun.com but I guess it’s inevitable that it’ll all be gone .

It’s old stuff that really wants a 32bit environment

Cul8r
________________________________
From: Alessandro Sangiuliano ***@***.***>
Sent: Saturday, January 8, 2022 7:09:47 PM
To: neozeed/xMach ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [neozeed/xMach] The annoying old compiler (Issue #3)


Hello, can I ask you, when you have a bit of time, to provide the old gcc compiler and binutils?

oskit archives seems unreacheable right now.

Thank you

—
Reply to this email directly, view it on GitHub<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fneozeed%2FxMach%2Fissues%2F3&data=04%7C01%7C%7Cd15615732a894e0dcaae08d9d2976295%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637772369904901714%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=MG1oAcSa3VkCPKUblcctDOe3j8J%2Fi8PqNyt7ISAloXM%3D&reserved=0>, or unsubscribe<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACE46DY3FBS52QOHIDY6GG3UVALPXANCNFSM5LQP5TOQ&data=04%7C01%7C%7Cd15615732a894e0dcaae08d9d2976295%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637772369904901714%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=DcwHmT1QkFw9rQVKxp0SZbODXoCV4dq2kq%2B39%2F3PK%2BI%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cd15615732a894e0dcaae08d9d2976295%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637772369904901714%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=MhY%2B6KD%2FWwbB0MmoaTv3PzMDgZowwxGisAYXtnf8Zbk%3D&reserved=0> or Android<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cd15615732a894e0dcaae08d9d2976295%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637772369905058378%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ELGPnzTqeHb8CCMMJjeHpR%2BpAdxYZorGMoO7jEItbuI%3D&reserved=0>.

**Comment by neozeed** [comment]
Crap I forgot …. But it’s here somewhere…?  I know I put it somewhere

**Comment by neozeed** [comment]
https://vpsland.superglobalmegacorp.com/install/Linux-i386/OSKit/i586-linux2.tar.gz

Read the 404 page for user and password 

more here 


https://virtuallyfun.com/wordpress/2021/06/09/xmach/

And the toolkit as part of oskit 

https://virtuallyfun.com/wordpress/2020/09/03/building-oskit/

**Comment by AlessandroSangiuliano** [comment]
Thak you finally i got it!. Time to build.

My goal is to get the kernl I need it to do some development and experiments, I'm also hacking on gnumach and doing some comparison between mach 3 and mach 4. I also have osfmk.

I'd like to make this mach 4 and osmk to build on modern compilers, and have them free to use to develop somethin on top of them

**Comment by neozeed** [comment]
Best of luck!  Mach is a strange beast with many twisty tunnels...

I haven't tried GCC 3/4 at all with any of them...  And GCC beyond that point is most definitely going to introduce further issues.
